Remove phase 42
softwareconstruction240/autograder pull request #334
Opened 2024-04-25 06:36 UTC by 19mdavenport

This removes phase 42 for quality and keeps track of phases using enums instead of strings and ints

2024-04-27 05:40 UTC, pawlh requested changes

2024-04-27 05:40 UTC, pawlh commented on src/main/java/edu/byu/cs/controller/SubmissionController.java
Line 203 should be a try-catch that uses `Phase.valueOf(phase)` instead of `PhaseUtils.getPhaseByString(phase)`. Right now this endpoint is generating a 400 error

2024-04-27 05:40 UTC, pawlh commented on src/main/java/edu/byu/cs/controller/SubmissionController.java
maybe
```
Phase phaseEnum = null;
try {
    phaseEnum = Phase.valueOf(phase);
} catch (IllegalArgumentException e) {
    LOGGER.error("Invalid phase", e);
    halt(400, "Invalid phase");
}
```

2024-04-27 18:31 UTC, 19mdavenport commented on src/main/java/edu/byu/cs/controller/SubmissionController.java
I didn't think about that endpoint. Thank you

2024-04-28 20:05 UTC, pawlh approved these changes

2024-04-28 22:41 UTC, merged